logged_topics: "
    /rosout
    /tf
    /robot_pose
    /cmd_vel
    /goal
    /mileage
    /motor_status
    /head/actual_state
    /head/cmd_light_state
    /head/commanded_state
    /barrier_status
    /battery_state
    /bumper
    /charger_status
    /rfid
    /diagnostics
    /SetPTUState/goal
    /ResetPtu/goal
    /EBC/parameter_updates
    /Charger/parameter_updates
    /topological_navigation/Route
    /topological_navigation/Statistics
    /current_node
    /current_edge
    /closest_node
    /monitored_navigation/monitored_nav_event
    /monitored_navigation/srv_pause_requested
    /monitored_navigation/stuck_on_carpet
    /monitored_navigation/pause_requested
    /do_backtrack/goal
    /speak/goal
    /mary_tts/speak
    /strands_emails/goal
    /strands_image_tweets/goal
    /pygame_player_negotiation
    /chargingServer/goal
    /chargingServer/result
    /chargingServer/cancel
    /docking/goal
    /docking/result
    /docking/cancel
    /undocking/goal
    /undocking/result
    /undocking/cancel
    /map_updates
    /move_base/NavfnROS/plan
    /move_base/current_goal
    /move_base/DWAPlannerROS/global_plan
    /move_base/DWAPlannerROS/local_plan
    /move_base/goal
    /execute_policy_mode/Statistics
    /task_executor/events
    /current_schedule
    /wait_node/goal
    /wait_node/result
    /wait_node/cancel
"
