nodes:
    - "ChargingPoint"
    - "Station"
    - "WayPoint8"
    - "WayPoint2"
    - "Eingang"
    - "Rezeption"
    - "WayPoint17"
    - "WayPoint35"
    - "WayPoint26"
    - "Cafeteria"
    - "Lift2"
    - "WayPoint7"
    - "WayPoint12"
    - "WayPoint19"
    - "WayPoint21"
    - "WayPoint28"
    - "Feuerloescher"
    - "WayPoint39"
    - "Konferenzraum"
    - "WayPoint43"
    - "WayPoint47"
    - "WayPoint32"
    - "WayPoint45"
    - "WayPoint48"
    - "WayPoint34"
    - "List1"
    - "WayPoint14"
