nodes:
- WayPoint71
- WayPoint72
- WayPoint73
- WayPoint74
- ChargingPoint
- Rezeption
- WayPoint19
- WayPoint21
- Eingang
- Feuerloescher
- Konferenzraum
- Lift2
- Seminarraum
- Station
- WayPoint12
- WayPoint2
- WayPoint28
- WayPoint32
- WayPoint39
- WayPoint43
- WayPoint45
- WayPoint47
- WayPoint51
- WayPoint53
- WayPoint54
- WayPoint55
- WayPoint56
- WayPoint57
- WayPoint59
- WayPoint60
- WayPoint61
- WayPoint62
- WayPoint63
- WayPoint66
- WayPoint7
- WayPoint82
- WayPoint83
- WayPoint84
- WayPoint85
- WayPoint86
- WayPoint91
- WayPoint87
- WayPoint8
- WayPoint81
- WayPoint90
- WayPoint26
- Frisoer
- WayPoint102
- WayPoint50
- Cafeteria
- WayPoint35
- WayPoint101
- WayPoint17
- WayPoint100
- WayPoint49
- WayPoint103
- WayPoint104
- Kapelle
- WayPoint14
- WayPoint105
- WayPoint106
- WayPoint76
- WayPoint52
- Lift1
- WayPoint48
- WayPoint34
- WayPoint58
- Teekueche
- WayPoint107
- WayPoint108
- WayPoint109
- WayPoint110
