nodes:
- WayPoint52
- WayPoint28
- WayPoint76
- ChargingPoint
- Kapelle
- Station
- Teekueche
- WayPoint14
- WayPoint82
- WayPoint2
- WayPoint66
- WayPoint35
- Eingang
- WayPoint81
- WayPoint26
- WayPoint86
- WayPoint49
- WayPoint50
- WayPoint51
- WayPoint48
- WayPoint53
- WayPoint54
- WayPoint56
- WayPoint58
- WayPoint32
- WayPoint59
- WayPoint47
- WayPoint43
- Cafeteria
- WayPoint34
- WayPoint19
- WayPoint60
- WayPoint84
- WayPoint39
- WayPoint87
- WayPoint8
- Rezeption
- WayPoint17
- Frisoer
- Lift2
- WayPoint7
- WayPoint21
- WayPoint12
- WayPoint63
- WayPoint85
- WayPoint62
- WayPoint55
- WayPoint83
- WayPoint57
- Feuerloescher
- Konferenzraum
- Lift1
- WayPoint61
- WayPoint45
