nodes:
- ChargingPoint
- WayPoint34
- WayPoint52
- WayPoint75
- WayPoint53
- WayPoint56
- WayPoint61
- WayPoint7
- Lift1
- WayPoint14
- WayPoint51
- WayPoint77
- WayPoint50
- WayPoint49
- WayPoint12
- WayPoint78
- Cafeteria
- WayPoint8
- Rezeption
- WayPoint35
- WayPoint45
- WayPoint58
- WayPoint59
- WayPoint32
- WayPoint82
- WayPoint57
- WayPoint54
- WayPoint55
- WayPoint47
- WayPoint83
- WayPoint60
- WayPoint43
- WayPoint84
- WayPoint63
- WayPoint85
- WayPoint17
- Eingang
- Station
- WayPoint2
- WayPoint26
- WayPoint87
- WayPoint66
- Konferenzraum
- Feuerloescher
- WayPoint39
- WayPoint48
- WayPoint62
- WayPoint28
- WayPoint21
- WayPoint19
- Lift2
- WayPoint76
- WayPoint81
- WayPoint86
